name: design_system
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - lib/assets/illustrations/
    - lib/assets/icons/

  fonts:
    - family: Klasik
      fonts:
        - asset: lib/fonts/Klasik-Regular.otf
          weight: 400
    - family: Manrope
      fonts:
        - asset: lib/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: lib/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: lib/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: lib/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: lib/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
